### PR TITLE
fix(callbakc): Callback does not redirect back to the requested url

### PR DESCRIPTION
**Pull request by guillaume-chervet**
#779

### CODE REVIEW

**Review by Thodor12 — COMMENTED** [review]
I'm not sure if this tackles the root cause, this seems to only affect cases where there is no state provided, which (provided in the original issue linked) isn't the case. I tested this locally just now by changing up the code to this and it doesn't fix it.

**Comment by Thodor12** [comment]
Isn't it more likely that `isMounted` becomes false because you're not awaiting the promise?

**Comment by guillaume-chervet** [comment]
Thank you for your help. I cannot reproduce your error.
I am interrested why do you have isMouted=false

Can you share more of you code logic ?

**Comment by Thodor12** [comment]
> Thank you for your help. I cannot reproduce your error. I am interrested why do you have isMouted=false
> 
> Can you share more of you code logic ? @Thodor12

My code logic isn't anything amazingly spectacular, I'm only using the OidcSecure component inside my router to lock everything down after the /dashboard route, I am however not using a silent signin URL (because of the iframe restrictions due to X-Frame-Options header).

Full config:
```js
function getAuthority() {
    if (Environment.OIDC_AUTHORITY !== undefined) {
        return Environment.OIDC_AUTHORITY;
    } else {
        return `${window.location.protocol}//auth.${window.location.host}`;
    }
}

export function GetOIDCConfiguration(): OidcConfiguration {
    return {
        client_id: Environment.OIDC_CLIENT_ID!,
        authority: getAuthority(),
        redirect_uri: window.location.origin + "/authentication/callback",
        scope: "openid profile email offline_access",
        service_worker_relative_url: '/OidcServiceWorker.js',
        service_worker_only: true
    }
};
```

**Comment by Thodor12** [comment]
However my best guess is still that [on this line](https://github.com/AxaGuilDEv/react-oidc/blob/c9aca5e82e2e450b6a31e04176455768b2c12ced/packages/react/src/oidc/core/default-component/Callback.component.tsx#L41) you're just calling the async method, which is essentially just a promise and not executed (and awaited).
This then causes the return function to be called first, which according to React it's documentation is a cleanup function which will reset `isMounted` to false, after this happens the promise will start to execute and will end up in the first if statement seeing that `isMounted` is false.
It's not a straight guarantee that this might happen, it depends on the device it's thread scheduling system what is executed first, which is probably why it's inconsistent.

**Comment by Thodor12** [comment]
I'll try the alpha0 version you just published after I'm done with work 👍🏻

**Comment by Thodor12** [comment]
The issue still exists in alpha0

**Comment by guillaume-chervet** [comment]
Hi @Thodor12 ,
can you share some code with your provider and more?

isMounted should never be called. You should have a behavior that refresh your OidcProvider.

**Comment by Thodor12** [comment]
In any case here is the router, maybe that is enough info?
```tsx
export function Router() {
    return (
        <BrowserRouter>
            <OidcProvider configuration={GetOIDCConfiguration()}>
                <Routes>
                    <Route element={<Layout />}>
                        <Route path="/" element={<Home />} />

                        <Route path="/dashboard" element={<OidcSecure><Outlet /></OidcSecure>}>
                            <Route index element={<Dashboard />} />
                            <Route path="worklists">
                                <Route index element={<WorkListIndex />} />
                            </Route>
                        </Route>
                    </Route>
                </Routes>
            </OidcProvider>
        </BrowserRouter>
    )
}
```

**Comment by Thodor12** [comment]
Also I can confirm that `isMounted` isn't the issue, I just tested by placing some loggers inside the dist JS file manually to see what the variable is, and it was true. So I think it does push an entry into the history, but like you said there's nothing which refreshes the OidcProvider.

**Comment by guillaume-chervet** [comment]
What happen if you set the code like that?

`export function Router() {
    return (
 
            <OidcProvider configuration={GetOIDCConfiguration()}>
       <BrowserRouter>
                <Routes>
                    <Route element={<Layout />}>
                        <Route path="/" element={<Home />} />

                        <Route path="/dashboard" element={<OidcSecure><Outlet /></OidcSecure>}>
                            <Route index element={<Dashboard />} />
                            <Route path="worklists">
                                <Route index element={<WorkListIndex />} />
                            </Route>
                        </Route>
                    </Route>
                </Routes>
        </BrowserRouter>
            </OidcProvider>

    )
}`

**Comment by Thodor12** [comment]
> What happen if you set the code like that?
> 
> ` export function Router() { return (
> 
> ```
>         <OidcProvider configuration={GetOIDCConfiguration()}>
>    <BrowserRouter>
>             <Routes>
>                 <Route element={<Layout />}>
>                     <Route path="/" element={<Home />} />
> 
>                     <Route path="/dashboard" element={<OidcSecure><Outlet /></OidcSecure>}>
>                         <Route index element={<Dashboard />} />
>                         <Route path="worklists">
>                             <Route index element={<WorkListIndex />} />
>                         </Route>
>                     </Route>
>                 </Route>
>             </Routes>
>     </BrowserRouter>
>         </OidcProvider>
> 
> )
> ```
> 
> } `
> 
> note: I tried it and i can reproduce your error. I will specify it inside the readme.

Unfortunately this one still didn't work for me

**Comment by Thodor12** [comment]
I'm gonna try isolate the problem by removing some of my other dependencies, maybe they're the issue

**Comment by Thodor12** [comment]
I've finally found the determining factor, it works with the setup you've described, provided you do NOT use `<React.StrictMode>`.
For some reason if you wrap your application within this component (which is what CRA does by default) it blocks the redirect from happening, something that you could look into?

**Comment by guillaume-chervet** [comment]
Thank you yeah definitly it is necessary to investigate

**Comment by jgregory-apogee** [comment]
I was able to work around this for now by wrapping my `<OidcProvider>` tags outside of `<React.StrictMode>`.  That lets me keep strict mode for the rest of my codebase.

**Comment by guillaume-chervet** [comment]
Which version of react are you using?
I do not have this problem on mine wicth strict mode with react 17

**Comment by guillaume-chervet** [comment]
Oh thank you i can reproduce it. It will be easier to fix !

**Pull request merged**
