### PR TITLE
Popup login

### PR DESCRIPTION
**Pull request by Maxinger15**
## Before this PR
Before it was not possible to login via a popup window, even it is supported by oidc-client-js.

## After this PR
I added the support for popups. Use popup_redirect_uri instead of redirect_uri in the config and 
there will open a Popup instead of redirecting you to the login page. With this your SPA keep open during login and no user interactions get lost.

### CODE REVIEW

**Comment by guillaume-chervet** [comment]
Hi @Maxinger15 ,did you manage to make it works?

Why do you need the popup mode? The world is using the default mode ( facebook, google, Microsoft, etc). For the user UX the other mode seems better.

**Comment by Maxinger15** [comment]
Hi, the code itself is running, but I am currently fighting with lerna and the test files because since I changed the files to success the lint test, the spec.ts files throw many errors about false types and interfaces. I am not sure if it is because I changed in manny files type... to interface ... to success the lint. But I am not sure how youbwas able to success the lint in the latest release, becaus I had to edit files i never touched. If you have time next week may we phone and you he

**Comment by guillaume-chervet** [comment]
I'am sorry, I'am out of computer until 17 august. 
@oyouf , do you have time to help @Maxinger15 ?

**Comment by guillaume-chervet** [comment]
Hi @Maxinger15, I really think it is a bad idea to integrate the popup login inside that repository.
I really think it it a bad UX practice and it will couple us more to oidc client. It will also complexify to much the code.

You may publish it from your own fork. @oyouf, @arnaudforaison, what do you think about it?

**Pull request closed without merging**
